import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { BOX_PRICES } from '../lib/types';
import { money } from '../lib/format';
import { useShop } from '../lib/store';
import { useDialog } from '../lib/useDialog';
import { usePresence } from '../lib/usePresence';
import { CookieTile } from './Cookie';
import { ArrowRight, Minus, Plus, X } from 'lucide-react';
function ReviewSlotRow({ box }) {
    const { flavours, remove } = useShop();
    const filled = [];
    for (const f of flavours) {
        const n = box.items[f.id] ?? 0;
        for (let i = 0; i < n; i++)
            filled.push(f.id);
    }
    const cols = box.size === 4 ? 'grid-cols-4 max-w-[200px]' : 'grid-cols-6';
    return (_jsx("ul", { className: `grid w-full ${cols} gap-1.5`, children: Array.from({ length: box.size }).map((_, i) => {
            const flavourId = filled[i];
            const flavour = flavourId ? flavours.find((f) => f.id === flavourId) : undefined;
            return (_jsx("li", { className: `relative aspect-square rounded-full flex items-center justify-center transition-all ${flavour
                    ? 'shadow-xs border border-line-soft'
                    : 'border border-dashed border-[#d8cdbf] bg-cream/50'}`, children: flavour ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "h-full w-full overflow-hidden rounded-full slot-pop", children: _jsx(CookieTile, { art: flavour.art, seedKey: `rev-slot-${box.id}-${flavour.id}-${i}`, photo: flavour.photo, className: "h-full w-full", inset: 0, fit: "cover" }) }), _jsx("button", { type: "button", onClick: () => remove(flavour.id), "aria-label": `Remove one ${flavour.name}`, className: "absolute -top-1 -right-1 z-10 grid h-3.5 w-3.5 place-items-center rounded-full bg-brick text-white shadow-xs transition-transform active:scale-90", children: _jsx(X, { className: "h-2 w-2", strokeWidth: 3, "aria-hidden": "true" }) })] })) : (_jsx("span", { className: "text-[10px] font-bold text-ink-faint/50", "aria-hidden": "true", children: i + 1 })) }, i));
        }) }));
}
export function ReviewSheet() {
    const { reviewOpen, closeReview, boxes, boxCount, orderTotal, flavours, add, remove, addBox, openCheckout, totalCookies, canAdd, } = useShop();
    const { ref } = useDialog(reviewOpen, closeReview);
    const { mounted, isClosing } = usePresence(reviewOpen, 240);
    if (!mounted)
        return null;
    return (_jsxs("div", { className: `fixed inset-0 z-[70] flex items-end justify-center md:items-center ${isClosing ? 'pointer-events-none' : ''}`, children: [_jsx("button", { type: "button", "aria-label": "Close your order", onClick: closeReview, className: `${isClosing ? 'fade-exit' : 'fade-enter'} absolute inset-0 bg-cocoa/45 backdrop-blur-[2px]` }), _jsxs("div", { ref: ref, role: "dialog", "aria-modal": "true", "aria-label": "Your order", className: `${isClosing ? 'sheet-exit' : 'sheet-enter'} relative max-h-[88dvh] w-full overflow-y-auto rounded-t-[30px] bg-cream px-5 pt-4 pb-[max(20px,env(safe-area-inset-bottom))] shadow-lift md:max-w-[460px] md:rounded-[30px] md:pb-6`, children: [_jsx("div", { className: "mx-auto mb-4 h-1 w-10 rounded-full bg-ink/15 md:hidden", "aria-hidden": "true" }), _jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "label-caps text-[10px] text-ink-soft", children: "Review your box" }), _jsx("h2", { className: "font-display text-[26px] leading-tight text-ink", children: "Your order" })] }), _jsx("button", { type: "button", onClick: closeReview, "aria-label": "Close", className: "grid h-10 w-10 shrink-0 place-items-center rounded-full border border-line bg-shell text-ink transition-transform hover:scale-105 active:scale-95", children: _jsx(X, { className: "h-4 w-4", "aria-hidden": "true" }) })] }), _jsx("div", { className: "mt-5 space-y-4", children: boxes.map((b, i) => {
                            const count = boxCount(b);
                            const items = flavours.filter((f) => (b.items[f.id] ?? 0) > 0);
                            return (_jsxs("section", { className: "rounded-[22px] border border-line bg-[#faf6f0] p-4 sm:p-5 shadow-xs transition-all", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("span", { className: "label-caps rounded-full bg-brick px-3 py-1.5 text-[10px] font-bold text-white", children: ["Box ", i + 1, " \u00B7 ", b.size, " cookies"] }), _jsxs("span", { className: "label-caps text-[10px] font-semibold text-ink-soft", children: [count, " of ", b.size, " filled"] })] }), _jsx("div", { className: "mt-3.5 rounded-[16px] border border-line-soft bg-shell/80 p-2.5", children: _jsx(ReviewSlotRow, { box: b }) }), _jsx("ul", { className: "mt-3.5 space-y-2.5 divide-y divide-line-soft", children: items.length === 0 ? (_jsx("li", { className: "py-2 text-[13.5px] text-ink-soft text-center", children: "Nothing in this box yet. Select flavours to fill." })) : (items.map((f) => (_jsxs("li", { className: "flex items-center justify-between gap-3 pt-2.5 first:pt-0", children: [_jsxs("div", { className: "flex items-center gap-2.5 min-w-0 flex-1", children: [_jsx("div", { className: "h-9 w-9 shrink-0 overflow-hidden rounded-full border border-line-soft bg-shell", children: _jsx(CookieTile, { art: f.art, seedKey: `rev-item-${b.id}-${f.id}`, photo: f.photo, className: "h-full w-full", inset: 2 }) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("p", { className: "truncate text-[13.5px] font-semibold text-ink", children: f.name }), _jsx("p", { className: "text-[11px] text-ink-soft/75", children: f.allergens.join(', ') })] })] }), _jsxs("div", { className: "flex items-center gap-1.5 shrink-0", children: [_jsx("button", { type: "button", onClick: () => remove(f.id), "aria-label": `Remove one ${f.name}`, className: "press-apple grid h-7 w-7 place-items-center rounded-full border border-line bg-shell text-ink transition-colors hover:border-ink/40 active:scale-95", children: _jsx(Minus, { className: "h-3 w-3", "aria-hidden": "true" }) }), _jsx("span", { className: "w-5 count-pop text-center text-[13px] font-bold text-ink", children: b.items[f.id] }, b.items[f.id]), _jsx("button", { type: "button", onClick: () => add(f.id), disabled: !canAdd(f.id), "aria-label": `Add one ${f.name}`, className: "press-apple grid h-7 w-7 place-items-center rounded-full border border-line bg-shell text-ink transition-colors hover:border-ink/40 active:scale-95 disabled:opacity-30 disabled:cursor-not-allowed", children: _jsx(Plus, { className: "h-3 w-3", "aria-hidden": "true" }) })] })] }, f.id)))) }), _jsxs("div", { className: "mt-3.5 flex items-baseline justify-between gap-3 border-t border-line-soft pt-3", children: [_jsxs("span", { className: "text-[13px] text-ink-soft", children: ["Box of ", b.size] }), _jsx("span", { className: "font-display text-[18px] font-bold text-ink", children: money(BOX_PRICES[b.size]) })] })] }, b.id));
                        }) }), boxes.length < 4 ? (_jsx("button", { type: "button", onClick: addBox, className: "press-apple mt-4 w-full rounded-full border border-line bg-shell py-3 text-[11px] font-bold tracking-[0.09em] text-ink uppercase transition-all hover:border-ink/40 active:scale-95", children: "+ Add another box" })) : null, _jsxs("div", { className: "mt-5 flex items-baseline justify-between gap-3 border-t border-line pt-4", children: [_jsx("span", { className: "label-caps text-[11px] text-ink-soft", children: "Total" }), _jsx("span", { className: "count-pop font-display text-[32px] sm:text-[36px] font-bold leading-none text-ink", children: money(orderTotal) }, orderTotal)] }), _jsxs("button", { type: "button", onClick: () => {
                            closeReview();
                            openCheckout(1);
                        }, disabled: totalCookies === 0, className: "press-apple mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full bg-brick px-6 py-4 text-[12px] font-bold tracking-[0.09em] text-white uppercase shadow-sm transition-all hover:bg-brick-dark active:scale-95 disabled:cursor-not-allowed disabled:bg-line disabled:text-ink-faint", children: [_jsxs("span", { children: ["Checkout \u00B7 ", money(orderTotal)] }), _jsx(ArrowRight, { className: "h-3.5 w-3.5", "aria-hidden": "true" })] })] })] }));
}
